### ISSUE TITLE
Export to CSV/TSV not working

### ISSUE THREAD

**Issue by akalajee** [allegro/turnilo#185]
When trying to export raw data to CSV/TSV, it generates the following error on Master. Bug is not on 1.6.0

Client Error: {"message":"Uncaught TypeError: Cannot read property 'toJS' of undefined","file":"http://localhost:9091/main.js?v=1.7.0","line":40,"column":3446,"stack":"TypeError: Cannot read property 'toJS' of undefined\n    at o (http://localhost:9091/app.0e38de4b4fd0e6e017b3.js:28:107673)\n    at n.r (http://localhost:9091/app.0e38de4b4fd0e6e017b3.js:28:107515)\n    at Object.l (http://localhost:9091/main.js?v=1.7.0:40:3325)\n    at Object.invokeGuardedCallback (http://localhost:9091/main.js?v=1.7.0:48:4486)\n    at Object.invokeGuardedCallbackAndCatchFirstError (http://localhost:9091/main.js?v=1.7.0:48:4603)\n    at h (http://localhost:9091/main.js?v=1.7.0:40:4250)\n    at y (http://localhost:9091/main.js?v=1.7.0:40:4718)\n    at b (http://localhost:9091/main.js?v=1.7.0:40:4875)\n    at Array.forEach (<anonymous>)\n    at g (http://localhost:9091/main.js?v=1.7.0:40:4519)"}

I debugged the code in download.ts:
export function download({ dataset, options }: DataSetWithTabOptions, fileFormat: FileFormat, fileName?: string): void 
 and I am receiving dataset = null

**Comment by adrianmroz** [comment]
Thanks for catching this mistake. We succesfully reproduced this error and we will look into it.

**Comment by adrianmroz** [comment]
So issue is with this line:

https://github.com/allegro/turnilo/blob/master/src/client/modals/raw-data-modal/raw-data-modal.tsx#L280

Because of bind and loose type of `Dataset`, I didn't notice error. `download` accepts object with dataset inside and options. Options are of type `TabulatorOptions` from `plywood`. For header button we create them from `Essence` with function: 

https://github.com/allegro/turnilo/blob/master/src/client/utils/tabular-options/tabular-options.ts
