### ISSUE TITLE
Client timeout

### ISSUE THREAD

**Issue by Laboltus** [allegro/turnilo#261]
Is it possible to increase request timeout in Turnilo ? Now it returns error "Query error client timeout" after 60 seconds. I tried to increase hardcoded .timeout(60000) in src/client/utils/ajax/ajax.ts. But now it returns "502 Bad Gateway The server returned an invalid or incomplete response" after 2 min.

**Comment by mkuthan** [comment]
60 seconds seems to be a lot for getting the response from Turnilo server. I would avoid to increase this timeout in the code but feel free to prepare a PR with support for custom timeout value in the Turnilo configuration file.

**Comment by Laboltus** [comment]
Could you please explain why do you want to avoid the increase ? Default timeout for druid query is 300 seconds and I guess Turnlino should work with it. I traced our requests and I saw how Druid returns the result (after 2 mins for example), but Tunlilo already shows timeout on UI.

**Comment by mkuthan** [comment]
Turnilo is data exploratory tool and but it requires quick response from the server. If not Druid cluster will be flooded by requests from users hitting browser F5. Please keep in mind that Turnilo/Plywood do not support query cancellation nor query queuing with queue size limit.

But I'm going to discuss this request in our team. Finally this is a timeout between browser and the Turnilo Backend, there is also a configurable timeout between Turnilo backend and Druid cluster (with an inconsistency in the code, see below) and finally default timeout in Druid broker (but it can be overwritten in query context):

https://github.com/allegro/turnilo/blob/7e3c4d5ba7b48f6b203f5d9875fbb68cce0a6dc6/src/common/models/cluster/cluster.ts#L89

https://github.com/allegro/turnilo/blob/7e3c4d5ba7b48f6b203f5d9875fbb68cce0a6dc6/src/server/utils/requester/requester.ts#L57

This issue is also somehow related #236.

**Comment by Laboltus** [comment]
Sorry, but I don't understand how this could protect from F5 flooding. Every F5 refresh sends query to Druid regardless of timeout. Moreover, since we get timeout error in UI, we will push F5 even more often and generate more and more heavy requests to Druid.

**Comment by adrianmroz** [comment]
Ok, we have timeout value in configuration and we should use it in application. Let's sketch plan for this task!

1. We should everywhere use timeout from cluster configuration. 
a. requester.ts shouldn't have own default, it will get value from config, so it will have value
b. ajax.ts also should use value from config
2. We should add some constant to client timeout to accommodate browser-turnilo communication. For now, let's pick value. It's impossible to select correct one so I don't think we should delegate that to the user via config. Just `const` in code.
