### ISSUE TITLE
Unify time formatting across whole app.

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#288]
Right now we have formatting logic in `time.ts` and specific logic in `Table` and `LineChart` visualisation. We need to identify common parts and extract them. We also should consider if any inconsistencies are necessary and maybe we could simplify current behaviour.

**Comment by mkuthan** [comment]
Design proposal for datetime formatting:

General rules:
- format 24h instead of am/pm
- no times like 23:59 if it means end of the day
- single time column in the excel format instead of compound column like [from, to], always formatted as ISO

Default datetime format: 30 Dec 2018 7:59 - 1 Jan 2019 8:55

Default datetime format should be shortened if:
- current year (from and to): 1 Jan 7:59 - 3 Jan 8:55
- for full-day: 30 Dec 2018 - 1 Jan 2019
- for full-day and current year: 1 Jan - 3 Jan
- for single day and current year: 1 Jan

**Comment by adrianmroz** [comment]
Repuropse code changes from #277
