### ISSUE TITLE
Line chart does not work with split on dimensions filtered in exclude mode

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#387]
![turnilo-exclude-err](https://user-images.githubusercontent.com/14329097/56421675-2ca16500-6293-11e9-9bcf-9a01bcbd1bc4.png)

**Comment by adrianmroz** [comment]
1.14 or just tip of master?

**Comment by l2dy** [comment]
> 1.14 or just tip of master?

Both.

**Comment by l2dy** [comment]
Can you reproduce this bug?

**Comment by adrianmroz** [comment]
Yup!

So problem is here: https://github.com/allegro/turnilo/blob/master/src/client/components/selectable-string-filter-menu/selectable-string-filter-menu.tsx#L210..L218

In filter we always select values and add to colors (legend). Because we add value to colors it's converted to having filter but main filter contradicts it (we require value and exclude it at the same time) so there's no data to be presented.

**Comment by adrianmroz** [comment]
Closed via #562
