### ISSUE TITLE
Infromation needed to add new features

### ISSUE THREAD

**Issue by viveksatasiya** [allegro/turnilo#481]
Hello all,

We want to use turnilo for our project. We have some requirements & to fulfil those requirements, we need to extend turnilo. We have gone through the code of this project & found immutable-class as dependency. We have also checked that module but still have some doubts. So if you can help us to make understand then it will be great help to us.

Can you please give us more insight about how to use immutable-class module? Here are some questions.

1. What are the benefits of using immutable-class?
2. If we extend baseimmutable class then we need to pass two types, one is JSType and another one is ValueType. What is that? & how they differ to each other?
3. What is the use of BackComp?
4. What finalize method do?

Thanks in advance.

**Comment by adrianmroz** [comment]
Hi!

Main benefit of immutable-class is automatic serialization/deserialization. ImmutableJS Records don't provide that for custom fields. Because of that, we want to use immutable-class only for structures that are used on client and server. Mostly that's representation of turnilo configuration - AppSettings and whole hierarchy of DataCube information (with dimensions, measures and so on). In contrast, Essence and it's fields are not needed to be serialised - we use Records from ImmutableJS. You should only use immutable-class when you want to extend turnilo data that's used on client and server. 

Ad 1. Serialization/Deserialization. Nothing else above Records from ImmutableJS. ImmutableJS uses weird techniques for serialising/deserializing it's own data structures and that prohibits usage of custom data types inside. There are also some helpers for tests.

Ad 2. One type is type of data inside class. That way consumer of class know what fields are there and what he can use. These are types of any complexity. Second type is type of serialised data - it must be subset of JSON types. If you extend BaseImmutabble - toJSON/fromJSOn will be derived automatically. If you extend Instance, you need to write those methods.

Ad 3. It is a mechanism for encoding backward compatibility. You shouldn't need that really.

Ad 4. It adds getters and setters to class prototype based on declared properties.

**Comment by viveksatasiya** [comment]
hi @adrianmroz,

Thanks for you quick response. Now I have more knowledge about immutable-class. Currently, I am exploring the code and trying to understand it so that I can extend it.

Again, Thanks a lot for your reply.

**Comment by viveksatasiya** [comment]
hi @adrianmroz,

Can you please give us more insight on Class & Instance? & What benefits are we getting by implementing them?

Thanks.

**Comment by adrianmroz** [comment]
Maybe we could move this discussion to slack: https://bit.ly/2WgiCNr ?

It is not really about benefits. If you need add something to `AppSettings`, you need to use immutable-class. If not, don't use it. 

Instance and Class are interfaces that you could implement on your own or you can use BaseImmutable class. Extending it like other classes in turnilo would provide default implementation for few methods.

**Comment by viveksatasiya** [comment]
Thanks for you reply.

Yes we can talk on this into slack channel. Link provided here is not working. Can you please give another link.

**Comment by adrianmroz** [comment]
Maybe direct link will work for you: https://app.slack.com/client/TEPHCGJTD/CEQMX06NB

**Comment by adrianmroz** [comment]
Close due to inactivity.
