### ISSUE TITLE
Different Split time granularity returns data with different timezone

### ISSUE THREAD

**Issue by wxpjimmy** [allegro/turnilo#486]
we use the latest build version(intalled by npm), our data are stored in utc timezone, we set turnilo timezone default to ASIA/HONE_KONG, and when we doing some query we found that when splitting by hour and minute, the result data is shown in ASIA/HONG_KONG timezone， but when splitting by day, the result data is still in UTC timezone, not the expected timezone,  this is wierd. Can anyone help explain this? or is this a bug?
![1571626188636](https://user-images.githubusercontent.com/3627160/67173210-87f21280-f3f0-11e9-858d-9eeb8585ec0c.jpg)
![1571626094162](https://user-images.githubusercontent.com/3627160/67173212-888aa900-f3f0-11e9-8dd9-0daffd136936.jpg)

**Comment by adrianmroz** [comment]
It is hard to tell because I'm not sure what are your steps.

Timezone in upper selector is presentation component. It affects how your selected date is converted to ISO date string in UTC and how to display your data back in UI. Change in this dropdown doesn't fetch new data. So If you got data in timezone A, changing dropdown will only affect presentation. So it could show old data in new timezone settings and days returned would no longer align with days asked due to hour offset.

First, could you confirm that this scenario (order is important for me) returns good data:
1. Set correct timezone
2. Select correct time filter
3. Select correct granularity

Only those three steps.

Second, if that's valid, what steps are needed to get you to situation on second picture.

**Comment by adrianmroz** [comment]
Train of toughest ahead:

I'm not sure if that's what happens but I noticed something counterintuitive:

Let's say you select dates: from 2 Oct 6:00 to 3 Oct 20:00. If you select granularity 1 Day, turnilo tries to bucket that time range. It creates buckets 2 Oct 0:00 - 2 Oct 23:59 and 3 Oct 0:00 - 3 Oct 23:59. 

Of course those buckets are limited by your original filter, so no data before 2 Oct 6:00 would slip into first bucket. But you asked for buckets. 

Then, Druid sends back this buckets with those time ranges. First time range has start date 2 Oct 0:00 and that we would convert with your selected timezone. If that happens that your selected timezone is different than timezone selected when sending query (you changed dropdown in meantime), some irregularities happen because 2 Oct 0:00 which should be start of the day is no longer start of the day because in different timezone it has some hours shifted.

And I think that what happens in your case.

Bigger problem is how we present date - **you have bucket 2 Oct 0:00 - 2 Oct 23:59 but you asked data starting at 2 Oct 6:00**. That is misleading. Maybe you should be able to pick day granularity only if your filter has boundaries on start and end of day?

**Comment by adrianmroz** [comment]
Only place where timezone has meaning in plywood is how to slice buckets on time with day (and larger) granularity. I think in this case, changing timezone should **resend query to plywood**.

**Comment by wxpjimmy** [comment]
appreciate your quick response @adrianmroz .
there's nothing difference to get the pic2 other than pic1 with only changing the split granularity from hour to day, the timezone is not changed.
i changed the query start time to the start of day but i still get the same result! 
And also when i change the split granulatiry, it indeed resend the query to plywood .

So what i expected is that the display in UI should be in accordance with each other,  or both UTC, or both Asia.  The one UTC one Asia behavior makes me confused!
===========
original query
![1571654216282](https://user-images.githubusercontent.com/3627160/67198600-e4c1ed00-f431-11e9-97ba-f424c2649ac0.jpg)

just change the split granularity:

![1571654256409](https://user-images.githubusercontent.com/3627160/67198599-e4c1ed00-f431-11e9-9739-b174214520a6.jpg)

**Comment by wxpjimmy** [comment]
[update]
just find something interesting.
the issue i met is due to our changing the data's default timezone from utc to Asia/Hong_Kong in the config，in such way,  the issue can  reproduce 100%。
but i found if we set the default timezone to utc and we select the Asia/Hong_kong timezone manually,  the issue is gone!
seems the default timezone setting is not working in all senarios( work in hour split granularity but not work in day split).

**Comment by adrianmroz** [comment]
Ok, I will try to reproduce your issue with different default timezone.

For sure I need to add query resend on timezone change.

And question for you - how do you feel about daily granularity when time range in filter does not align with start/end of the day? Like in my example - filter is 2 Oct 8:00 - 3 Oct 16:00 and granularity 1 Day. Returned data is labeled 2 Oct 0:00 - 2 Oct 23:59 but it has data only for 2 Oct 8:00 - 2 Oct 23:59. Is that weird? It seems weird for me, but also I'm not sure how I could make it clear in UI.

**Comment by adrianmroz** [comment]
I assume https://github.com/allegro/turnilo/pull/488 fixes issue? Reopen if not.
