### ISSUE TITLE
Slack invite link is not useable anymore

### ISSUE THREAD

**Issue by cedrics** [allegro/turnilo#566]
Hey, the slack invite link in the [Join us!](https://github.com/allegro/turnilo#join-us) section has run out. Is this still a way of communication you want to use? 
In course of the project I am currently doing some smaller question have come up and it would probably easier to clarify via Slack than github issues, that's why I am asking

**Comment by adrianmroz** [comment]
Slack invites are only valid for 2000 users. Probably Slack counts clicks on this link, and because it is in readme a lot of bots click on it. 

I generated new one, please try: https://join.slack.com/t/turnilo/shared_invite/enQtOTI4ODcxMjcyNjU2LTFlOTk5YWZlOGMyZDZhZWU3MGNjNDRhZmI1Y2UzNDlkZmY3YzYxYTJhYzIzMzc0MTc3MzA3OTE1NmQ5NDI1M2I

I will look into more robust solution.

**Comment by adrianmroz** [comment]
worth considering: https://github.com/rauchg/slackin
