### ISSUE TITLE
Timeouts in turnilo

### ISSUE THREAD

**Issue by adrianmroz** [allegro/turnilo#696]
We want to be more explicit about timeouts in turnilo and also fix few issues along the way.

General idea: Turnilo should be driven by timeouts on queries, everything else is safety measure

Timeouts on queries are passed as `query.context.timeout`. Administrator should be able to define timeout on cluster (just like now) and turnilo should respect `context` property on specific datasource (right now turnilo overrides timeout from `context`).

We should not pass timeout to druidRequesterFactory, because this timeout not only limit request time but will be passed into query context. That's bad for two reasons:
* We create requester for whole cluster, so we can't override timeout for data source (I'm not sure if we can afford creating requesters per data source)
* Timeout on query is in principal different than timeout on query request. Lets say we set timeout to 100ms. Druid could calculate result in 99ms, but due to network overhead it will timeout on plywood side.

We also want to give administrators ability to set timeouts purely for safety. For example if your server or druid cluster goes down, user should not wait indefinitely. Probably administrator don't need those timeouts because have some load balancer in the middle.

Two timeouts are:
* client timeout - timeout between user browser and turnilo backend
* server timeout - timeout between turnilo backend and druid. But please note, it is timeout of the whole request from the client. Plywood for one query from client can spawn multiple druid queries and often they are dependant so will result in waterfall. For example if you select 3 splits on Table visualisation, you can expect that whole request can take query timeout times 3. 

These timeouts should be defined on top level of config and should not depend on clusters/data sources. They are only for cases when something goes terribly wrong. In normal use, query timeouts would return errors and notify user about problem.

**Comment by mkuthan** [comment]
Great summary. I would also clarify that Turnilo should not set any timeouts by default (because there is no good defaults):

Druid Query timeout:
* if not defined (default) will be effectively "druid.server.http.defaultQueryTimeout"
* if defined, must be below "druid.server.http.maxQueryTimeout"

Turnilo client timeout
* if not defined (default) - browser does not timeout idle connection to the server
* if defined should be >>> effective Druid Query Timeout 

Turnilo server timeout:
* if not defined (default) - server does not timeout idle connection to the browser
* if defined should be >= Turnilo client timeout
