### ISSUE TITLE
Change data cube without resetting filter or split

### ISSUE THREAD

**Issue by chaochaocodes** [allegro/turnilo#785]
Changing between data cubes currently resets all parameters and shows the total of the data cube.  
- We would like an option to retain/save parameters for efficient reporting and circumvent manually remaking reports for each data cube
- Current hack:  change data cube query by updating the URL @

**Comment by adrianmroz** [comment]
> Changing between data cubes currently resets all parameters and shows the total of the data cube.  

That sounds like a bug, because if possible turnilo will keep filters, series and splits between detainees as long measures and dimensions names are the same. 

Code is here: https://github.com/allegro/turnilo/blob/master/src/common/models/essence/essence.ts#L417 If you skills you could debug it yourself. 

It's hard for me to investigate further without full bug report. I don't know if it's possible but I would need yours cubes configuration and what URL you have at the start.

**Comment by adrianmroz-allegro** [comment]
Feel free to reopen with full bug report.
