### ISSUE TITLE
Data Grid visualization for splits on 2 dimensions and 1 measure

### ISSUE THREAD

**Issue by mkuthan** [allegro/turnilo#80]
New Grid like visualization, one split for X axis, second for Y axis, single measure values in grid cells.
When column or row is selected, selected value is proposed as a new filter (include or exclude). When filter is applied, grid is transformed into single row or column. When cell is selected, selected value is proposed as new filters on both dimensions (X and Y, include or exlude). When filter is applied, grid is transformed into single cell.

![screen shot 2018-03-21 at 13 50 57](https://user-images.githubusercontent.com/1560526/37710771-f593c4f0-2d0e-11e8-8fd1-ed0eccf928ab.png)

**Comment by beibm** [comment]
Wow! This is an exciting feature and it is expected that this feature can be implemented as soon as possible.

**Comment by mkuthan** [comment]
Grid is somehow similar to heatmap visualization. Do we need grid visualization anymore?

**Comment by grzaks** [comment]
I was very disappointed to find out that turnilo doesn't have a good old pivot table visualization, where you can put some dimensions into rows and other into columns. 

Heatmap is not really an equivalent because sometimes we just need numbers, not colored boxes. I vote for making the grid visualization even if it's limited to one dimension on rows and 2nd dimension on columns and one metric. Wouldn't it be easy to "clone" heatmap visualization into grid one (just replacing graphics to text values?

Of course full-featured pivot table would be much better. I mean pivot table like in Excel where you can put more than one dimension into rows/cols and more than one metrics.

**Comment by adrianmroz** [comment]
Full fledged pivot table is impossible for turnilo UI right now. Turnilo understand splits as ordered set and series as another ordered set. In Pivot table you have splits and series intermixed as two ordered sets - columns and rows. Would be rather hard to conform those ways, more so if we add time shift. 

I think we could think about "numbered" heat map visualisation - 2 dimensions, one measure (time shift on tooltip). It has some technical challenges but nothing big.

On the other hand, we propose #539 - almost pivot table

**Comment by adrianmroz** [comment]
To be continued as heatmap setting in #430
